const fs = require('fs');
const path = require('path');

const replacements = {
    'Main.gd': [
        ['No writable portable project is available. Choose an RPG project directory.', '未找到可写的便携式项目。请选择一个 RPG 项目目录。'],
        ['Cannot create portable RPG project directory:', '无法创建便携式 RPG 项目目录：'],
        ['Packaged blank project template is missing.', '缺失打包的空白项目模板。'],
        ['Cannot write portable RPG project file:', '无法写入便携式 RPG 项目文件：'],
        ['Could not remember the last project beside the executable.', '无法在可执行文件旁记住上一次的项目。'],
        ['Could not replace portable settings.', '无法替换便携式设置。'],
        ['Could not finalize portable settings.', '无法完成便携式设置。'],
        ['"File"', '"文件"'],
        ['"Open Project…"', '"打开项目…"'],
        ['"Save Actor    Ctrl+S"', '"保存角色    Ctrl+S"'],
        ['"Edit"', '"编辑"'],
        ['"Available in a later phase"', '"在后续开发阶段可用"'],
        ['"Project"', '"项目"'],
        ['"New Dialogue…"', '"新建对话 (Dialogue)…"'],
        ['"New Quest…"', '"新建任务 (Quest)…"'],
        ['"New Story Graph…"', '"新建剧情节点 (Story Graph)…"'],
        ['"Build Content Pack…"', '"构建内容包…"'],
        ['"No project"', '"未打开项目"'],
        ['"  ● Offline  "', '"  ● 离线 (Offline)  "'],
        ['"Studio remains editable offline; connecting to 127.0.0.1."', '"Studio 离线状态下仍然可编辑；正在连接至 127.0.0.1。"'],
        ['"  PROJECT"', '"  项目 (Project)"'],
        ['"+ Actor"', '"+ 新建角色"'],
        ['"Duplicate"', '"复制"'],
        ['"Delete"', '"删除"'],
        ['"ACTORS"', '"角色列表 (ACTORS)"'],
        ['"  INSPECTOR"', '"  属性检查器 (Inspector)"'],
        ['"ID"', '"ID"'],
        ['"lowercase_resource_id"', '"小写的资源ID"'],
        ['"Display Name"', '"显示名称 (Display Name)"'],
        ['"Notes"', '"备注 (Notes)"'],
        ['"Tags"', '"标签 (Tags)"'],
        ['"comma, separated, tags"', '"使用逗号, 分隔, 多个标签"'],
        ['"Save Actor"', '"保存角色"'],
        ['"Actor stores RPG identity only.\\nCNPC model, AI, health, combat and animation\\nremain in CustomNPC+."', '"角色 (Actor) 仅存储 RPG 身份。\\nCNPC 模型、AI、生命值、战斗及动画\\n仍然在 CustomNPC+ 中管理。"'],
        ['"Create at least one Actor before creating a Dialogue."', '"创建对话 (Dialogue) 前，请至少创建一个角色 (Actor)。"'],
        ['"New Dialogue"', '"新对话"'],
        ['"New dialogue line."', '"新对话内容。"'],
        ['"Saved Dialogue:[/color] %s"', '"已保存对话 (Dialogue)：[/color] %s"'],
        ['"Deleted Dialogue:[/color] %s"', '"已删除对话 (Dialogue)：[/color] %s"'],
        ['"New Quest"', '"新任务"'],
        ['"Describe the player\'s goal."', '"描述玩家的目标任务。"'],
        ['"Defeat one Slime"', '"击败一只史莱姆 (Slime)"'],
        ['"Saved Quest:[/color] %s"', '"已保存任务 (Quest)：[/color] %s"'],
        ['"Deleted Quest:[/color] %s"', '"已删除任务 (Quest)：[/color] %s"'],
        ['"Create at least one Actor before creating a Story."', '"创建剧情节点前，请至少创建一个角色 (Actor)。"'],
        ['"New Story"', '"新剧情"'],
        ['"Saved Story:[/color] %s"', '"已保存剧情 (Story)：[/color] %s"'],
        ['"Deleted Story:[/color] %s"', '"已删除剧情 (Story)：[/color] %s"'],
        ['"Discarded unsaved Actor Inspector changes."', '"已舍弃未保存的角色属性修改。"'],
        ['"Invalid project"', '"无效的项目"'],
        ['"Opened project:[/color] %s (%d Actor(s), %d Dialogue(s), %d Quest(s), %d Story/Stories)"', '"已打开项目：[/color] %s (%d 角色, %d 对话, %d 任务, %d 剧情)"'],
        ['"Project opened with validation errors:[/color] %s"', '"项目打开时出现验证错误：[/color] %s"'],
        ['"Actors (%d)"', '"角色 (%d)"'],
        ['"Dialogues (%d)"', '"对话 (%d)"'],
        ['"Quests (%d)"', '"任务 (%d)"'],
        ['"Stories (%d)"', '"剧情 (%d)"'],
        ['"Selected Actor: [b]%s[/b]"', '"已选择角色：[b]%s[/b]"'],
        ['"New Actor"', '"新角色"'],
        ['"Created unsaved Actor: %s"', '"创建未保存角色：%s"'],
        ['" Copy"', '" 副本"'],
        ['"Duplicated Actor as unsaved resource: %s"', '"已复制角色为未保存资源：%s"'],
        ['"Delete Actor \'%s\'?\\nThis removes its JSON file."', '"确定要删除角色 \'%s\' 吗？\\n此操作将移除对应的 JSON 文件。"'],
        ['"Delete Actor"', '"删除角色"'],
        ['"Deleted Actor:[/color] %s"', '"已删除角色：[/color] %s"'],
        ['"Failed to delete Actor:[/color] %s"', '"删除角色失败：[/color] %s"'],
        ['"Actor ID already exists: %s"', '"角色 ID 已存在：%s"'],
        ['"Save rejected: duplicate Actor ID.[/color]"', '"保存被拒绝：重复的角色 ID。[/color]"'],
        ['"Saved"', '"已保存"'],
        ['"Save Actor *"', '"保存角色 *"'],
        ['"Saved Actor:[/color] %s"', '"已保存角色：[/color] %s"'],
        ['"Actor save failed. See Problems.[/color]"', '"角色保存失败。请查看“问题”面板。[/color]"'],
        ['var root := VBoxContainer.new()', 'var root := VBoxContainer.new()\n\tself.theme = ThemeManager.build_modern_theme()']
    ],
    'LiveWorkspace.gd': [
        ['"Debugger"', '"调试器 (Debugger)"'],
        ['"Player"', '"玩家 (Player)"'],
        ['"Story"', '"剧情 (Story)"'],
        ['"Start node ID"', '"起始节点 ID"'],
        ['"▶ Test"', '"▶ 测试"'],
        ['"■ Stop + Restore"', '"■ 停止并恢复"'],
        ['"Refresh"', '"刷新"'],
        ['"Runtime"', '"运行时"'],
        ['"State / Why Not Triggered"', '"状态 / 为何未触发"'],
        ['"Minecraft"', '"Minecraft (游戏内)"'],
        ['"Pick Actor"', '"拾取角色"'],
        ['"Pick Position"', '"拾取位置"'],
        ['"Pick Region"', '"拾取区域"'],
        ['"Pick Item"', '"拾取物品"'],
        ['"Pick Entity Type"', '"拾取实体类型"'],
        ['"Locate Selected Actor"', '"定位选中的角色"'],
        ['"Pick results appear here."', '"拾取结果将显示于此。"'],
        ['"Saved %s \'%s\' offline; use /dgrpg reload as fallback."', '"离线保存了 %s \'%s\'；请在游戏内使用 /dgrpg reload。"'],
        ['"  ● Minecraft Connected  "', '"  ● Minecraft 已连接  "'],
        ['"Minecraft Connected"', '"Minecraft 实时桥接已连接"'],
        ['"Minecraft Live Bridge offline"', '"Minecraft 实时桥接已离线"'],
        ['"Live Bridge protocol %s, DarkGrey RPG %s"', '"实时桥接协议版本 %s, DarkGrey RPG 版本 %s"'],
        ['"Minecraft Pick result: "', '"Minecraft 拾取结果： "'],
        ['"Pick in progress"', '"正在拾取中"'],
        ['"No online player"', '"暂无在线玩家"'],
        ['"PLAY TEST"', '"调试中 (PLAY TEST)"'],
        ['"Live"', '"实时 (Live)"'],
        ['"Quests"', '"任务列表 (Quests)"'],
        ['"Story Instances"', '"剧情实例 (Story Instances)"'],
        ['"Why Not Triggered / Last Condition"', '"为何未触发 / 最后条件"'],
        ['"Variables"', '"变量 (Variables)"'],
        ['"Live Actors (%d)"', '"实时活跃角色 (%d)"'],
        ['"Players (%d)"', '"玩家 (%d)"'],
        ['"Live command skipped: Minecraft is offline.[/color]"', '"实时命令被跳过：Minecraft 目前处于离线状态。[/color]"']
    ],
    'DialogueEditorWindow.gd': [
        ['title = "DarkGrey RPG — Dialogue Editor"', 'title = "DarkGrey RPG — 对话编辑器 (Dialogue Editor)"'],
        ['var root := VBoxContainer.new()', 'var root := VBoxContainer.new()\n\tself.theme = ThemeManager.build_modern_theme()'],
        ['"ID"', '"ID"'],
        ['"Title"', '"标题 (Title)"'],
        ['"Entry"', '"入口节点 (Entry)"'],
        ['"Speakers"', '"说话者 (Speakers)"'],
        ['"actor_id, another_actor"', '"actor_id, another_actor"'],
        ['"Actor resource IDs"', '"角色 (Actor) 资源 IDs"'],
        ['"Save Dialogue  Ctrl+S"', '"保存对话  Ctrl+S"'],
        ['"Search dialogue text"', '"搜索对话内容"'],
        ['"Find Next"', '"查找下一个"'],
        ['"Replace with"', '"替换为"'],
        ['"Replace All"', '"全部替换"'],
        ['"+ Line"', '"+ 文本 (Line)"'],
        ['"+ Choice"', '"+ 选项 (Choice)"'],
        ['"+ Jump"', '"+ 跳转 (Jump)"'],
        ['"+ End"', '"+ 结束 (End)"'],
        ['"Move Up"', '"上移"'],
        ['"Move Down"', '"下移"'],
        ['"Duplicate"', '"复制"'],
        ['"Delete"', '"删除"'],
        ['"Undo  Ctrl+Z"', '"撤销  Ctrl+Z"'],
        ['"Redo  Ctrl+Y"', '"重做  Ctrl+Y"'],
        ['"Delete Dialogue"', '"删除对话"'],
        ['"Select a Dialogue node."', '"请选择一个对话节点。"'],
        ['" NODE"', '" 节点 (NODE)"'],
        ['"Node ID"', '"节点 ID"'],
        ['"Speaker"', '"说话者 (Speaker)"'],
        ['"Text"', '"文本内容 (Text)"'],
        ['"Next"', '"下一步 (Next)"'],
        ['"Prompt"', '"提示词 (Prompt)"'],
        ['"Choices — one per line: label | next_node"', '"选项分支 (每行一个) 格式: 标签文本 | 目标节点"'],
        ['"Choice returns only through an End node. It cannot start a Quest."', '"选项只能通过 End 节点返回结果。它不能直接在这里开始任务。"'],
        ['"Target"', '"目标节点 (Target)"'],
        ['"Named Result"', '"命名结果 (Named Result)"'],
        ['"New dialogue line."', '"新对话内容。"'],
        ['"Continue"', '"继续"'],
        ['"Found in node %s"', '"在节点 %s 中找到"'],
        ['"No match"', '"未找到匹配项"'],
        ['"Replaced %d field(s)"', '"替换了 %d 个字段"'],
        ['"Duplicate Dialogue ID"', '"重复的对话 ID"'],
        ['"Saved"', '"已保存"'],
        ['"Validation failed — see main Problems panel"', '"验证失败 — 请查看主界面的“问题”面板"'],
        ['"Save Dialogue *  Ctrl+S"', '"保存对话 *  Ctrl+S"']
    ],
    'QuestEditorWindow.gd': [
        ['title = "DarkGrey RPG — Quest Editor"', 'title = "DarkGrey RPG — 任务编辑器 (Quest Editor)"'],
        ['var root := VBoxContainer.new()', 'var root := VBoxContainer.new()\n\tself.theme = ThemeManager.build_modern_theme()'],
        ['"ID"', '"ID"'],
        ['"Title"', '"标题 (Title)"'],
        ['"Description"', '"描述 (Description)"'],
        ['"Save Quest  Ctrl+S"', '"保存任务  Ctrl+S"'],
        ['"Delete Quest"', '"删除任务"'],
        ['"Undo  Ctrl+Z"', '"撤销  Ctrl+Z"'],
        ['"Redo  Ctrl+Y"', '"重做  Ctrl+Y"'],
        ['"Duplicate Dialogue ID"', '"重复的任务 ID"'], 
        ['"Saved"', '"已保存"'],
        ['"Validation failed — see main Problems panel"', '"验证失败 — 请查看主界面的“问题”面板"'],
        ['"Save Quest *  Ctrl+S"', '"保存任务 *  Ctrl+S"'],
        ['"Objectives"', '"目标 (Objectives)"'],
        ['"Groups"', '"组 (Groups)"'],
        ['"Select a Quest element."', '"请选择一个任务元素。"'],
        ['"+ Objective"', '"+ 目标 (Objective)"'],
        ['"+ Group"', '"+ 组 (Group)"'],
        ['"Delete"', '"删除"'],
        ['"Duplicate"', '"复制"']
    ],
    'StoryEditorWindow.gd': [
        ['title = "DarkGrey RPG — Story Editor"', 'title = "DarkGrey RPG — 剧情编辑器 (Story Editor)"'],
        ['var root := VBoxContainer.new()', 'var root := VBoxContainer.new()\n\tself.theme = ThemeManager.build_modern_theme()'],
        ['"ID"', '"ID"'],
        ['"Title"', '"标题 (Title)"'],
        ['"Save Story  Ctrl+S"', '"保存剧情  Ctrl+S"'],
        ['"Delete Story"', '"删除剧情"'],
        ['"Undo  Ctrl+Z"', '"撤销  Ctrl+Z"'],
        ['"Redo  Ctrl+Y"', '"重做  Ctrl+Y"'],
        ['"Saved"', '"已保存"'],
        ['"Save Story *  Ctrl+S"', '"保存剧情 *  Ctrl+S"'],
        ['"+ Event"', '"+ 事件 (Event)"'],
        ['"+ Condition"', '"+ 条件 (Condition)"'],
        ['"+ Action"', '"+ 行为 (Action)"'],
        ['"Entry Node"', '"入口节点 (Entry Node)"']
    ]
};

const baseDir = "E:/Java/MinecraftMod/DarkGrey_RPG/studio/scripts";

for (const [filename, fileReplacements] of Object.entries(replacements)) {
    const filePath = path.join(baseDir, filename);
    if (fs.existsSync(filePath)) {
        let content = fs.readFileSync(filePath, 'utf8');
        for (const [oldStr, newStr] of fileReplacements) {
            content = content.split(oldStr).join(newStr);
        }
        fs.writeFileSync(filePath, content, 'utf8');
        console.log(`Translated ${filename}`);
    } else {
        console.log(`File not found: ${filename}`);
    }
}
