gtnh.settings.blowdryerTag = 0.2.2

modName = DarkGrey RPG
modVersion = 0.3.2.1
modId = darkgrey_rpg
modGroup = darkgrey.rpg
useModGroupForPublishing = true

autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Developer

enableModernJavaSyntax = false
enableGenericInjection = true
generateGradleTokenClass = darkgrey.rpg.Tags
gradleTokenVersion = VERSION
replaceGradleTokenInFile =

apiPackage =
accessTransformersFile =
usesMixins = false
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage =
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false

usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
includeWellKnownRepositories = true
excludeWellKnownRepositories =
usesMavenPublishing = false

disableSpotless = false
disableCheckstyle = false

org.gradle.java.home = E\:/Java/jdk-25.0.1
org.gradle.java.installations.paths = E\:/Java/jdk-25.0.1,E\:/Java/jdk-21.0.7,E\:/Java/jdk-17.0.2
org.gradle.configuration-cache = true
org.gradle.parallel = true
