[CmdletBinding()]
param(
    [string] $RepositoryRoot = 'E:\Java\MinecraftMod\DarkGrey_RPG',
    [string] $ExePath = 'E:\Java\MinecraftMod\DarkGrey_RPG\dist\DarkGreyRPGStudio\DarkGreyRPGStudio.exe',
    [string] $ProjectDirectory = 'E:\Java\MinecraftMod\DarkGrey_RPG\.tooling\0314-s20-authoring-project',
    [string] $SettingsPath = 'E:\Java\MinecraftMod\DarkGrey_RPG\.tooling\0314-s13-s16-settings.json',
    [string] $EvidenceDirectory = 'E:\Java\MinecraftMod\DarkGrey_RPG\PLAN\0.3.1.4\evidence\final-live-post-choice-layout\s13-s16'
)

$ErrorActionPreference='Stop'
Add-Type -AssemblyName UIAutomationClient
Add-Type -AssemblyName UIAutomationTypes
Add-Type -AssemblyName System.Drawing
Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public static class S13S16Native{[DllImport("user32.dll")]public static extern bool SetForegroundWindow(IntPtr h);[DllImport("user32.dll")]public static extern bool MoveWindow(IntPtr h,int x,int y,int w,int hgt,bool repaint);[DllImport("user32.dll")]public static extern bool SetCursorPos(int x,int y);[DllImport("user32.dll")]public static extern void mouse_event(uint f,uint a,uint b,uint c,UIntPtr d);}'

$repo=[IO.Path]::GetFullPath($RepositoryRoot).TrimEnd('\');$tooling=[IO.Path]::GetFullPath((Join-Path $repo '.tooling')).TrimEnd('\');$planEvidence=[IO.Path]::GetFullPath((Join-Path $repo 'PLAN\0.3.1.4\evidence')).TrimEnd('\')
$project=[IO.Path]::GetFullPath($ProjectDirectory).TrimEnd('\');$exe=[IO.Path]::GetFullPath($ExePath);$settings=[IO.Path]::GetFullPath($SettingsPath);$evidence=[IO.Path]::GetFullPath($EvidenceDirectory).TrimEnd('\');$resultPath=Join-Path $evidence 's13-s16-inspector-theme-gate.json'
if(-not $project.StartsWith($tooling+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Gate project must remain below .tooling.'};if(-not $settings.StartsWith($tooling+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Gate settings must remain below .tooling.'};if(-not($evidence.StartsWith($tooling+'\',[StringComparison]::OrdinalIgnoreCase)-or$evidence.StartsWith($planEvidence+'\',[StringComparison]::OrdinalIgnoreCase))){throw 'Evidence path is outside allowed roots.'}
foreach($required in @($exe,(Join-Path $project 'project.json'),(Join-Path $project 'item_groups\currencies.json'))){if(-not(Test-Path -LiteralPath $required)){throw "Required path missing: $required"}}
New-Item -ItemType Directory -Path $evidence -Force|Out-Null

$desktop=[Windows.Automation.AutomationElement]::RootElement;$walker=[Windows.Automation.TreeWalker]::RawViewWalker;$process=$null
$state=[ordered]@{schema_version=1;status='FAIL';started_utc=[DateTime]::UtcNow.ToString('o');exe=$exe;exe_sha256=(Get-FileHash -LiteralPath $exe -Algorithm SHA256).Hash;exe_product_version=[Diagnostics.FileVersionInfo]::GetVersionInfo($exe).ProductVersion;exe_file_version=[Diagnostics.FileVersionInfo]::GetVersionInfo($exe).FileVersion;exe_bytes=(Get-Item $exe).Length;project=$project;evidence_directory=$evidence;screenshots=[Collections.Generic.List[string]]::new();gates=[Collections.Generic.List[object]]::new()}

function Visible($e){if($null-eq$e){return $false};try{$r=$e.Current.BoundingRectangle;return (-not$e.Current.IsOffscreen-and$r.Width-gt 0-and$r.Height-gt 0)}catch{return $false}}
function Find-Id($root,[string]$id,[int]$timeout=12){$c=[Windows.Automation.PropertyCondition]::new([Windows.Automation.AutomationElement]::AutomationIdProperty,$id);$until=[DateTime]::UtcNow.AddSeconds($timeout);do{try{foreach($x in $root.FindAll([Windows.Automation.TreeScope]::Descendants,$c)){if(Visible $x){return $x}}}catch{};Start-Sleep -Milliseconds 80}while([DateTime]::UtcNow-lt$until);throw "Visible AutomationId '$id' was not found."}
function Find-Name($root,[string]$name,[int]$timeout=12){$c=[Windows.Automation.PropertyCondition]::new([Windows.Automation.AutomationElement]::NameProperty,$name);$until=[DateTime]::UtcNow.AddSeconds($timeout);do{try{foreach($x in $root.FindAll([Windows.Automation.TreeScope]::Descendants,$c)){if(Visible $x){return $x}}}catch{};Start-Sleep -Milliseconds 80}while([DateTime]::UtcNow-lt$until);throw "Visible element '$name' was not found."}
function Ancestor($e,[Windows.Automation.ControlType]$type){for($i=0;$i-lt 20-and$null-ne$e;$i++){if($e.Current.ControlType-eq$type){return $e};$e=$walker.GetParent($e)};return $null}
function Process-Windows([int]$id){$c=[Windows.Automation.PropertyCondition]::new([Windows.Automation.AutomationElement]::ProcessIdProperty,$id);@($desktop.FindAll([Windows.Automation.TreeScope]::Descendants,$c)|Where-Object{Visible $_})}
function Find-Main([int]$id,[int]$timeout=25){$until=[DateTime]::UtcNow.AddSeconds($timeout);do{foreach($w in(Process-Windows $id)){if($w.Current.AutomationId-eq'RootWindow'){return $w}};Start-Sleep -Milliseconds 100}while([DateTime]::UtcNow-lt$until);throw "Studio RootWindow for $id was not found."}
function Focus-Main($main,[int]$wait=160){[S13S16Native]::SetForegroundWindow($main.Current.NativeWindowHandle)|Out-Null;Start-Sleep -Milliseconds $wait}
function Click-Point([double]$x,[double]$y,[switch]$right){[S13S16Native]::SetCursorPos([int]$x,[int]$y)|Out-Null;[S13S16Native]::mouse_event($(if($right){8}else{2}),0,0,0,[UIntPtr]::Zero);Start-Sleep -Milliseconds 100;[S13S16Native]::mouse_event($(if($right){16}else{4}),0,0,0,[UIntPtr]::Zero);Start-Sleep -Milliseconds 280}
function Click-Element($e){$r=$e.Current.BoundingRectangle;if($r.Width-le 0-or$r.Height-le 0){throw 'Element has no click target.'};Click-Point ($r.Left+$r.Width/2) ($r.Top+$r.Height/2)}
function Screenshot($main,[string]$name){Focus-Main $main 250;$r=$main.Current.BoundingRectangle;$bmp=[Drawing.Bitmap]::new([int]$r.Width,[int]$r.Height);try{$g=[Drawing.Graphics]::FromImage($bmp);try{$g.CopyFromScreen([int]$r.Left,[int]$r.Top,0,0,$bmp.Size)}finally{$g.Dispose()};$path=Join-Path $evidence $name;$bmp.Save($path,[Drawing.Imaging.ImageFormat]::Png);$full=[IO.Path]::GetFullPath($path);$state.screenshots.Add($full);return $full}finally{$bmp.Dispose()}}
function Average-Luminance([string]$path){$bmp=[Drawing.Bitmap]::new($path);try{$sum=0.0;$count=0;for($y=20;$y-lt$bmp.Height;$y+=20){for($x=20;$x-lt$bmp.Width;$x+=20){$c=$bmp.GetPixel($x,$y);$sum+=(0.2126*$c.R)+(0.7152*$c.G)+(0.0722*$c.B);$count++}};return [math]::Round($sum/$count,1)}finally{$bmp.Dispose()}}
function Configure([string]$theme){$cfg=[ordered]@{schema_version=1;theme=$theme;window_width=1540;window_height=900;window_maximized=$false;last_project=$project;recent_projects=@($project)};[IO.File]::WriteAllText($settings,($cfg|ConvertTo-Json -Depth 5)+"`n",[Text.UTF8Encoding]::new($false))}
function Start-Studio([string]$theme){Configure $theme;$si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=$exe;$si.WorkingDirectory=Split-Path -Parent $exe;$si.UseShellExecute=$false;$si.Environment['DARKGREYRPG_STUDIO_SETTINGS_PATH']=$settings;$script:process=[Diagnostics.Process]::Start($si);$main=Find-Main $process.Id;[S13S16Native]::MoveWindow($main.Current.NativeWindowHandle,20,20,1540,900,$true)|Out-Null;Focus-Main $main 900;return $main}
function Stop-Studio{if($null-eq$process-or$process.HasExited){return};$process.CloseMainWindow()|Out-Null;if(-not$process.WaitForExit(10000)){$process.Kill();$process.WaitForExit(5000)};$script:process=$null}
function Enter-Story($main){Focus-Main $main;$c=[Windows.Automation.PropertyCondition]::new([Windows.Automation.AutomationElement]::NameProperty,'史莱姆清理委托');$left=$main.Current.BoundingRectangle.Left;$item=$null;foreach($label in $main.FindAll([Windows.Automation.TreeScope]::Descendants,$c)){if((Visible $label)-and$label.Current.BoundingRectangle.Left-lt($left+350)){$candidate=Ancestor $label ([Windows.Automation.ControlType]::ListItem);if($null-ne$candidate){$item=$candidate;break}}};if($null-eq$item){throw 'Story ListItem was not found.'};$selection=$null;if(-not$item.TryGetCurrentPattern([Windows.Automation.SelectionItemPattern]::Pattern,[ref]$selection)){throw 'Story ListItem has no SelectionItemPattern.'};$selection.Select();Start-Sleep -Milliseconds 300;$enter=Find-Name $main '进入选中故事';$until=[DateTime]::UtcNow.AddSeconds(6);while(-not$enter.Current.IsEnabled-and[DateTime]::UtcNow-lt$until){Start-Sleep -Milliseconds 100;$enter=Find-Name $main '进入选中故事' 1};if(-not$enter.Current.IsEnabled){throw 'Enter Story did not enable.'};Click-Element $enter;Find-Id $main 'CanonicalStoryWorkspace' 15|Out-Null}
function Expand-Folder($main,[string]$name){$c=[Windows.Automation.PropertyCondition]::new([Windows.Automation.AutomationElement]::NameProperty,$name);foreach($x in $main.FindAll([Windows.Automation.TreeScope]::Descendants,$c)){$p=$null;if($x.TryGetCurrentPattern([Windows.Automation.ExpandCollapsePattern]::Pattern,[ref]$p)){if($p.Current.ExpandCollapseState-eq[Windows.Automation.ExpandCollapseState]::Collapsed){$p.Expand();Start-Sleep -Milliseconds 180};return}};throw "Folder '$name' expander was not found."}
function Find-LeftResourceButton($main,[string]$displayName){$c=[Windows.Automation.PropertyCondition]::new([Windows.Automation.AutomationElement]::NameProperty,$displayName);$left=$main.Current.BoundingRectangle.Left;foreach($label in $main.FindAll([Windows.Automation.TreeScope]::Descendants,$c)){if(-not(Visible $label)){continue};$button=Ancestor $label ([Windows.Automation.ControlType]::Button);if($null-ne$button-and$button.Current.BoundingRectangle.Left-lt($left+400)){return $button}};throw "Left resource '$displayName' was not found."}
function Select-Resource($main,[string]$folder,[string]$displayName,[string]$identityLabel,[string]$identityValue,[string[]]$tags,[string]$kind){
    Focus-Main $main;Expand-Folder $main $folder;$label=$null;$value=$null;$matched=$false
    for($attempt=1;$attempt -le 3 -and -not $matched;$attempt++){
        Focus-Main $main 80;Click-Element(Find-LeftResourceButton $main $displayName);$until=[DateTime]::UtcNow.AddSeconds(3)
        do{try{$label=Find-Id $main 'ResourceInspectorIdentityLabel' 1;$value=Find-Id $main 'ResourceInspectorIdentityValue' 1;if($label.Current.Name-eq$identityLabel-and$value.Current.Name-eq$identityValue){$matched=$true;break}}catch{};Start-Sleep -Milliseconds 80}while([DateTime]::UtcNow-lt$until)
    }
    if(-not$matched){$actualLabel=if($null-eq$label){'<missing>'}else{$label.Current.Name};$actualValue=if($null-eq$value){'<missing>'}else{$value.Current.Name};throw "$kind Inspector identity mismatch: '$actualLabel'/'$actualValue'."}
    $display=Find-Id $main 'ResourceInspectorDisplayNameValue';$tagValue=Find-Id $main 'ResourceInspectorTagsValue';if($display.Current.Name-ne$displayName){throw "$kind display name mismatch '$($display.Current.Name)'."};foreach($tag in $tags){if($tagValue.Current.Name-notlike"*$tag*"){throw "$kind tags omit '$tag': '$($tagValue.Current.Name)'."}}
    $inspector=Find-Id $main 'CanonicalInspectorScrollViewer';$ownership=@($inspector.FindAll([Windows.Automation.TreeScope]::Descendants,[Windows.Automation.PropertyCondition]::new([Windows.Automation.AutomationElement]::NameProperty,'拥有/引用状态'))|Where-Object{Visible $_});if($ownership.Count-ne 0){throw "$kind Inspector still exposes 拥有/引用状态 as a main field."};$scroll=$null;$canScroll=$inspector.TryGetCurrentPattern([Windows.Automation.ScrollPattern]::Pattern,[ref]$scroll)
    return [ordered]@{kind=$kind;display_name=$display.Current.Name;identity_label=$label.Current.Name;identity_value=$value.Current.Name;tags=$tagValue.Current.Name;ownership_main_field_present=$false;scroll_pattern=$canScroll}
}
function Open-Resource($main,[string]$folder,[string]$displayName){Focus-Main $main;Expand-Folder $main $folder;$button=Find-LeftResourceButton $main $displayName;$r=$button.Current.BoundingRectangle;Click-Point ($r.Left+$r.Width/2) ($r.Top+$r.Height/2) -right;$edit=Find-Name $desktop '编辑' 5;Click-Element $edit;Find-Id $main 'CanonicalStoryWorkspaceGraph' 12|Out-Null;Start-Sleep -Milliseconds 400}
function Select-Node($main,[string]$id){Focus-Main $main;$node=Find-Id $main ("CanonicalGraphNode_{0}"-f$id);$r=$node.Current.BoundingRectangle;Click-Point ($r.Left+[math]::Min(80,$r.Width/3)) ($r.Top+18);Start-Sleep -Milliseconds 350}
function Open-Problems($main){Focus-Main $main;$text=Find-Name $main '问题';$item=Ancestor $text ([Windows.Automation.ControlType]::ListItem);if($null-eq$item){throw 'Problems tab ListItem was not found.'};Click-Element $item;Start-Sleep -Milliseconds 500;$list=Find-Id $main 'ProblemList' 5;$r=$list.Current.BoundingRectangle;if($r.Height-lt 80){throw "Problems pane did not expand; height=$($r.Height)."};foreach($header in @('严重性','资源','问题','字段')){Find-Name $list $header 3|Out-Null};return [ordered]@{expanded=$true;height=[math]::Round($r.Height,1);headers=@('严重性','资源','问题','字段')}}
function Gate([string]$id,[string]$description,[scriptblock]$action){$entry=[ordered]@{id=$id;description=$description;status='FAIL';started_utc=[DateTime]::UtcNow.ToString('o')};try{$entry.details=&$action;$entry.status='PASS'}catch{$entry.error=$_.Exception.Message;$state.gates.Add([pscustomobject]$entry);throw};$entry.completed_utc=[DateTime]::UtcNow.ToString('o');$state.gates.Add([pscustomobject]$entry)}

try{
    $main=Start-Studio 'Dark';Enter-Story $main
    Gate 'S13' 'Actor, Actor Group, Item and Item Group inspectors use field hierarchy with IDs and tags and omit ownership status' {
        $cases=@(
            [ordered]@{folder='角色';name='酒馆老板';label='NPC_ID';id='tavern_boss';tags=@('merchant','npc');kind='角色';file='s13-actor-dark.png'},
            [ordered]@{folder='角色';name='史莱姆';label='Group_ID';id='slimes';tags=@('monster','group');kind='角色组';file='s13-actor-group-dark.png'},
            [ordered]@{folder='物品';name='铜币';label='Item_ID';id='copper_coin';tags=@('currency','reward');kind='物品';file='s13-item-dark.png'},
            [ordered]@{folder='物品';name='货币组';label='Group_ID';id='currencies';tags=@('currency','group');kind='物品组';file='s13-item-group-dark.png'})
        $results=[Collections.Generic.List[object]]::new();foreach($case in $cases){$result=Select-Resource $main $case.folder $case.name $case.label $case.id $case.tags $case.kind;$result.screenshot=Screenshot $main $case.file;$results.Add([pscustomobject]$result)};return [ordered]@{resource_count=$results.Count;resources=$results;all_omit_ownership_main_field=(@($results|Where-Object ownership_main_field_present).Count-eq 0)}
    }
    Gate 'S16' 'Graph, Choice, Inspector and Problems are readable in Dark and Light themes' {
        $session=Get-Content -LiteralPath (Join-Path $project 'resources\canonical\sessions\slime_cleanup_session.json') -Raw|ConvertFrom-Json;$choice=@($session.graph.nodes|Where-Object type -eq 'choice'|Select-Object -First 1);if($null-eq$choice){throw 'Choice fixture node was not found.'}
        Open-Resource $main '会话' '史莱姆清理会话';try{Click-Element(Find-Name $main '适应全部图节点' 3)}catch{};Select-Node $main ([string]$choice.id);Find-Id $main 'CanonicalInspectorScrollViewer' 4|Out-Null;$darkProblems=Open-Problems $main;$darkPath=Screenshot $main 's16-dark-graph-choice-inspector-problems.png';Stop-Studio
        $main=Start-Studio 'Light';Enter-Story $main;Open-Resource $main '会话' '史莱姆清理会话';try{Click-Element(Find-Name $main '适应全部图节点' 3)}catch{};Select-Node $main ([string]$choice.id);Find-Id $main 'CanonicalInspectorScrollViewer' 4|Out-Null;$lightProblems=Open-Problems $main;$lightPath=Screenshot $main 's16-light-graph-choice-inspector-problems.png';$darkLum=Average-Luminance $darkPath;$lightLum=Average-Luminance $lightPath;if($lightLum-le($darkLum+35)){throw "Light/Dark screenshot luminance separation is too small: dark=$darkLum light=$lightLum."};return [ordered]@{dark=[ordered]@{theme='Dark';screenshot=$darkPath;average_luminance=$darkLum;problems=$darkProblems};light=[ordered]@{theme='Light';screenshot=$lightPath;average_luminance=$lightLum;problems=$lightProblems};luminance_delta=[math]::Round($lightLum-$darkLum,1);choice_node_id=[string]$choice.id;covered=@('Graph','Inspector','Choice','Problems')}
    }
    Stop-Studio;$state.status='PASS'
}catch{$state.error=$_.Exception.Message;try{if($null-ne$process-and-not$process.HasExited){$m=Find-Main $process.Id 2;Screenshot $m 'failure.png'|Out-Null}}catch{};try{Stop-Studio}catch{}}
finally{$state.completed_utc=[DateTime]::UtcNow.ToString('o');[IO.File]::WriteAllText($resultPath,($state|ConvertTo-Json -Depth 20)+"`n",[Text.UTF8Encoding]::new($false))}
$state|ConvertTo-Json -Depth 20
if($state.status-ne'PASS'){exit 1}
