#DarkGrey RPG utility window layout
#Thu Sep 17 11:00:02 CST 2026
window.settings.width=380
audio.voice=0.4970588235294118
dialogue.charactersPerSecond=120.0
audio.gramophone=1.0
dialogue.opacity=0.0
window.settings.centerXRatio=0.5011709601873536
ui.theme=AZURE
window.settings.centerYRatio=0.5
window.settings.height=267
audio.sessionMusic=0.4970588235294118
ui.textScale=1.5
