#DarkGrey RPG utility window layout
#Thu Sep 17 11:00:25 CST 2026
window.settings.width=380
audio.voice=1.0
dialogue.charactersPerSecond=30.0
audio.gramophone=1.0
dialogue.opacity=0.8
window.settings.centerXRatio=0.5011709601873536
ui.theme=CHARCOAL
window.settings.centerYRatio=0.5
window.settings.height=267
audio.sessionMusic=1.0
ui.textScale=1.0
