using System.ComponentModel;
using DarkGreyRPG.Studio.Core.Actors;
using DarkGreyRPG.Studio.Core.Validation;
namespace DarkGreyRPG.Studio.Core.Quests;
public sealed class QuestDocument : INotifyPropertyChanged
{
    private QuestResource _resource; private QuestResource? _saved; private bool _isNew; private string? _sourcePath; private IReadOnlyList<ValidationIssue> _issues = [];
    private QuestDocument(QuestResource resource, string? path, bool isNew) { _resource = resource; _sourcePath = path; _isNew = isNew; _saved = isNew ? null : resource.WithId(resource.Id); Revalidate(); }
    public event PropertyChangedEventHandler? PropertyChanged;
    public string Id { get => _resource.Id; set { _resource = Copy(id: value); Changed(nameof(Id)); } } public string Title { get => _resource.Title; set { _resource = Copy(title: value); Changed(nameof(Title)); } } public string DisplayName { get => _resource.DisplayName; set { _resource = Copy(displayName: value); Changed(nameof(DisplayName)); } } public string Description { get => _resource.Description; set { _resource = Copy(description: value); Changed(nameof(Description)); } } public string HomeStoryId { get => _resource.HomeStoryId; set { _resource = Copy(homeStoryId: value); Changed(nameof(HomeStoryId)); } } public IList<QuestObjectiveResource> Objectives => _resource.Objectives; public IList<ObjectiveGroupResource> ObjectiveGroups => _resource.ObjectiveGroups; public QuestMetadata Metadata { get => _resource.Metadata; set { _resource = Copy(metadata: value); Changed(nameof(Metadata)); } } public string? SourcePath => _sourcePath; public bool IsNew => _isNew; public bool IsDirty => _isNew || !SavedContentEquals(); public IReadOnlyList<ValidationIssue> ValidationIssues => _issues; public IReadOnlyList<ValidationIssue> ValidationErrors => _issues.Where(i => i.Severity == ValidationSeverity.Error).ToArray();
    public static QuestDocument CreateNew(string id, string title = "新任务") { var o = QuestObjectiveResource.Interact("objective", "与角色交互", "actor"); return new(new QuestResource { Id = id, Title = title, DisplayName = title, Description = "新任务", HomeStoryId = "uncategorized", Objectives = [o], ObjectiveGroups = [new ObjectiveGroupResource { Id = "all", Mode = "ALL", Objectives = [o.Id] }] }, null, true); }
    public static QuestDocument FromResource(QuestResource resource, string path) => new(resource, Path.GetFullPath(path), false);
    public void SetMetadata(QuestMetadata metadata) { _resource = Copy(metadata: metadata); Changed(nameof(Metadata)); }
    public QuestResource ToResource() => new() { SchemaVersion = 2, Id = Id, Title = Title, DisplayName = DisplayName, Description = Description, HomeStoryId = HomeStoryId, Objectives = Objectives.Select(x => x.Clone()).ToList(), ObjectiveGroups = ObjectiveGroups.Select(x => x.Clone()).ToList(), Metadata = Metadata.Clone() };
    public void AddObjective(QuestObjectiveResource objective, string? groupId = null) { Objectives.Add(objective); var group = ObjectiveGroups.FirstOrDefault(g => g.Id == groupId) ?? ObjectiveGroups.First(); group.Objectives.Add(objective.Id); Changed(nameof(Objectives)); } public bool RemoveObjective(string id) { var x = Objectives.FirstOrDefault(o => o.Id == id); if (x is null) return false; Objectives.Remove(x); foreach (var g in ObjectiveGroups) g.Objectives.RemoveAll(v => v == id); Changed(nameof(Objectives)); return true; } public void AddGroup(ObjectiveGroupResource group) { ObjectiveGroups.Add(group); Changed(nameof(ObjectiveGroups)); } public void ReplaceObjectives(IEnumerable<QuestObjectiveResource> values) { _resource = Copy(objectives: values.Select(x => x.Clone()).ToList()); Changed(nameof(Objectives)); } public void ReplaceGroups(IEnumerable<ObjectiveGroupResource> values) { _resource = Copy(groups: values.Select(x => x.Clone()).ToList()); Changed(nameof(ObjectiveGroups)); }
    public void Revalidate() { _issues = QuestValidator.Validate(ToResource(), _isNew ? ActorIdPolicy.NewResource : ActorIdPolicy.ExistingResource); PropertyChanged?.Invoke(this, new(nameof(ValidationIssues))); PropertyChanged?.Invoke(this, new(nameof(ValidationErrors))); }
    internal void MarkSaved(string path) { _sourcePath = Path.GetFullPath(path); _isNew = false; _resource = ToResource(); _saved = _resource.WithId(_resource.Id); Revalidate(); PropertyChanged?.Invoke(this, new(nameof(IsNew))); PropertyChanged?.Invoke(this, new(nameof(IsDirty))); }
    private QuestResource Copy(string? id = null, string? title = null, string? displayName = null, string? description = null, string? homeStoryId = null, List<QuestObjectiveResource>? objectives = null, List<ObjectiveGroupResource>? groups = null, QuestMetadata? metadata = null) => new() { SchemaVersion = _resource.SchemaVersion, Id = id ?? Id, Title = title ?? Title, DisplayName = displayName ?? DisplayName, Description = description ?? Description, HomeStoryId = homeStoryId ?? HomeStoryId, Objectives = objectives ?? Objectives.Select(x => x.Clone()).ToList(), ObjectiveGroups = groups ?? ObjectiveGroups.Select(x => x.Clone()).ToList(), Metadata = metadata?.Clone() ?? Metadata.Clone() }; private void Changed(string name) { PropertyChanged?.Invoke(this, new(name)); Revalidate(); PropertyChanged?.Invoke(this, new(nameof(IsDirty))); }
    private bool SavedContentEquals() { try { return _saved is not null && string.Equals(QuestSerializer.Serialize(_resource, ActorIdPolicy.ExistingResource), QuestSerializer.Serialize(_saved, ActorIdPolicy.ExistingResource), StringComparison.Ordinal); } catch (QuestException) { return false; } }
}
