using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using DarkGreyRPG.Studio.Core.Actors;
using DarkGreyRPG.Studio.Core.Validation;
namespace DarkGreyRPG.Studio.Core.Quests;
public static class QuestSerializer
{
    private static readonly JsonSerializerOptions Options = new() { AllowTrailingCommas = false, Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping, PropertyNameCaseInsensitive = false, ReadCommentHandling = JsonCommentHandling.Disallow, UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow, WriteIndented = true, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull };
    public static string Serialize(QuestResource resource, ActorIdPolicy policy = ActorIdPolicy.NewResource) { var normalized = new QuestResource { SchemaVersion = 2, Id = resource.Id, Title = resource.Title, DisplayName = string.IsNullOrWhiteSpace(resource.DisplayName) ? resource.Title : resource.DisplayName, Description = resource.Description, HomeStoryId = string.IsNullOrWhiteSpace(resource.HomeStoryId) ? "uncategorized" : resource.HomeStoryId, Objectives = resource.Objectives.Select(x => x.Clone()).ToList(), ObjectiveGroups = resource.ObjectiveGroups.Select(x => x.Clone()).ToList(), Metadata = resource.Metadata.Clone() }; ThrowIfInvalid(QuestValidator.Validate(normalized, policy)); return JsonSerializer.Serialize(normalized, Options).Replace("\r\n", "\n", StringComparison.Ordinal) + "\n"; }
    public static QuestResource Deserialize(string json, string? sourcePath = null) { ArgumentException.ThrowIfNullOrWhiteSpace(json); try { using var doc = JsonDocument.Parse(json, new JsonDocumentOptions { AllowTrailingCommas = false, CommentHandling = JsonCommentHandling.Disallow }); var e = doc.RootElement; if (e.ValueKind != JsonValueKind.Object) throw new JsonException("Quest JSON root must be an object."); var r = Parse(e); var issues = QuestValidator.Validate(r, ActorIdPolicy.ExistingResource).ToList(); if (!string.IsNullOrWhiteSpace(sourcePath) && !string.Equals(Path.GetFileName(sourcePath), r.Id + ".json", StringComparison.Ordinal)) issues.Add(new("quest.filename.mismatch", "Quest file name must match its ID.", "id")); ThrowIfInvalid(issues); return r; } catch (QuestValidationException) { throw; } catch (Exception ex) when (ex is JsonException or InvalidOperationException or FormatException) { throw new QuestDataException("Quest JSON is invalid or contains unsupported fields.", ex); } }
    public static QuestResource Read(string path) { try { return Deserialize(File.ReadAllText(path), path); } catch (QuestException) { throw; } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) { throw new QuestDataException($"Could not read Quest file '{path}'.", ex); } }
    private static QuestResource Parse(JsonElement e) { Ensure(e, ["schema_version", "id", "title", "display_name", "description", "home_story_id", "objectives", "objective_groups", "metadata"]); var v = Req(e, "schema_version").GetInt32(); if (v is not (1 or 2)) throw new JsonException("Unsupported Quest schema_version."); var title = Req(e, "title").GetString() ?? string.Empty; return new QuestResource { SchemaVersion = v, Id = Req(e, "id").GetString() ?? string.Empty, Title = title, DisplayName = v == 1 ? title : Req(e, "display_name").GetString() ?? string.Empty, Description = Req(e, "description").GetString() ?? string.Empty, HomeStoryId = v == 1 ? "uncategorized" : Req(e, "home_story_id").GetString() ?? string.Empty, Objectives = Objectives(Req(e, "objectives")), ObjectiveGroups = Groups(Req(e, "objective_groups")), Metadata = Metadata(Req(e, "metadata")) }; }
    private static List<QuestObjectiveResource> Objectives(JsonElement e) { if (e.ValueKind != JsonValueKind.Array) throw new JsonException("objectives must be an array."); var result = new List<QuestObjectiveResource>(); foreach (var x in e.EnumerateArray()) { Ensure(x, ["id", "type", "description", "entity", "item", "metadata", "required", "dimension", "x", "y", "z", "radius", "actor_id"]); result.Add(new QuestObjectiveResource { Id = Req(x, "id").GetString() ?? string.Empty, Type = Req(x, "type").GetString() ?? string.Empty, Description = Req(x, "description").GetString() ?? string.Empty, Entity = Str(x, "entity"), Item = Str(x, "item"), ItemMetadata = Int(x, "metadata"), Required = Int(x, "required"), Dimension = Int(x, "dimension"), X = Num(x, "x"), Y = Num(x, "y"), Z = Num(x, "z"), Radius = Num(x, "radius"), ActorId = Str(x, "actor_id") }); } return result; }
    private static List<ObjectiveGroupResource> Groups(JsonElement e) { if (e.ValueKind != JsonValueKind.Array) throw new JsonException("objective_groups must be an array."); return e.EnumerateArray().Select(x => { Ensure(x, ["id", "mode", "objectives"]); return new ObjectiveGroupResource { Id = Req(x, "id").GetString() ?? string.Empty, Mode = Req(x, "mode").GetString() ?? string.Empty, Objectives = Strings(Req(x, "objectives")) }; }).ToList(); }
    private static QuestMetadata Metadata(JsonElement e) { Ensure(e, ["notes", "tags"]); return new QuestMetadata { Notes = Str(e, "notes") ?? string.Empty, Tags = e.TryGetProperty("tags", out var t) ? Strings(t) : [] }; }
    private static List<string> Strings(JsonElement e) { if (e.ValueKind != JsonValueKind.Array) throw new JsonException("Expected string array."); return e.EnumerateArray().Select(x => x.ValueKind == JsonValueKind.String ? x.GetString() ?? string.Empty : throw new JsonException("Expected string." )).ToList(); }
    private static JsonElement Req(JsonElement e, string n) => e.TryGetProperty(n, out var v) ? v : throw new JsonException($"{n} is required."); private static string? Str(JsonElement e, string n) => e.TryGetProperty(n, out var v) && v.ValueKind != JsonValueKind.Null ? v.GetString() : null; private static int? Int(JsonElement e, string n) => e.TryGetProperty(n, out var v) && v.ValueKind != JsonValueKind.Null ? v.GetInt32() : null; private static double? Num(JsonElement e, string n) => e.TryGetProperty(n, out var v) && v.ValueKind != JsonValueKind.Null ? v.GetDouble() : null; private static void Ensure(JsonElement e, IEnumerable<string> names) { var allowed = names.ToHashSet(StringComparer.Ordinal); foreach (var p in e.EnumerateObject()) if (!allowed.Contains(p.Name)) throw new JsonException($"Unsupported Quest field '{p.Name}'."); } private static void ThrowIfInvalid(IEnumerable<ValidationIssue> issues) { var all = issues.ToArray(); if (all.Any(i => i.Severity == ValidationSeverity.Error)) throw new QuestValidationException(all); }
}
