using System.Text.RegularExpressions;
using DarkGreyRPG.Studio.Core.Actors;
using DarkGreyRPG.Studio.Core.Validation;

namespace DarkGreyRPG.Studio.Core.Quests;
public static partial class QuestValidator
{
    private static readonly string[] Types = ["kill_entity", "collect_item", "interact_actor", "reach_location"];
    public static IReadOnlyList<ValidationIssue> Validate(QuestResource resource, ActorIdPolicy policy = ActorIdPolicy.ExistingResource)
    {
        ArgumentNullException.ThrowIfNull(resource); var i = new List<ValidationIssue>();
        if (resource.SchemaVersion is not (1 or 2)) i.Add(new("quest.schema.unsupported", "Quest schema_version must be 1 or 2.", "schema_version"));
        ValidateId(resource.Id, policy, i); if (string.IsNullOrWhiteSpace(resource.Title)) i.Add(new("quest.title.required", "Quest title is required.", "title")); if (resource.SchemaVersion >= 2 && string.IsNullOrWhiteSpace(resource.DisplayName)) i.Add(new("quest.display_name.required", "Quest display_name is required.", "display_name")); if (string.IsNullOrWhiteSpace(resource.Description)) i.Add(new("quest.description.required", "Quest description is required.", "description")); if (resource.SchemaVersion >= 2 && string.IsNullOrWhiteSpace(resource.HomeStoryId)) i.Add(new("quest.home_story_id.required", "Quest home_story_id is required.", "home_story_id"));
        var ids = new HashSet<string>(StringComparer.Ordinal); foreach (var o in resource.Objectives ?? []) { if (string.IsNullOrWhiteSpace(o.Id) || !ids.Add(o.Id)) i.Add(new("quest.objective.id.duplicate", $"Quest objective ID '{o.Id}' is missing or duplicated.", "objectives")); if (!Types.Contains(o.Type, StringComparer.Ordinal)) { i.Add(new("quest.objective.type.invalid", $"Unsupported objective type '{o.Type}'.", "objectives")); continue; } if (string.IsNullOrWhiteSpace(o.Description)) i.Add(new("quest.objective.description.required", $"Objective '{o.Id}' description is required.", "objectives")); if (o.Type is "kill_entity" && string.IsNullOrWhiteSpace(o.Entity)) i.Add(new("quest.objective.entity.required", $"Objective '{o.Id}' entity is required.", "objectives")); if (o.Type is "collect_item" && (string.IsNullOrWhiteSpace(o.Item) || o.ItemMetadata is null)) i.Add(new("quest.objective.item.required", $"Objective '{o.Id}' item and metadata are required.", "objectives")); if (o.Type is "interact_actor" && string.IsNullOrWhiteSpace(o.ActorId)) i.Add(new("quest.objective.actor.required", $"Objective '{o.Id}' actor_id is required.", "objectives")); if (o.Type is "reach_location" && (o.Dimension is null || o.X is null || o.Y is null || o.Z is null || o.Radius is null || o.Radius <= 0)) i.Add(new("quest.objective.location.invalid", $"Objective '{o.Id}' reach_location coordinates and positive radius are required.", "objectives")); if (o.Type is not "reach_location" && (o.Required is null || o.Required <= 0)) i.Add(new("quest.objective.required.invalid", $"Objective '{o.Id}' required must be positive.", "objectives")); }
        var groups = new HashSet<string>(StringComparer.Ordinal); var memberships = new Dictionary<string, int>(StringComparer.Ordinal); foreach (var g in resource.ObjectiveGroups ?? []) { if (string.IsNullOrWhiteSpace(g.Id) || !groups.Add(g.Id)) i.Add(new("quest.group.id.duplicate", $"Quest group ID '{g.Id}' is missing or duplicated.", "objective_groups")); if (g.Mode is not ("ALL" or "ANY" or "SEQUENCE")) i.Add(new("quest.group.mode.invalid", $"Quest group '{g.Id}' has invalid mode.", "objective_groups")); if (g.Objectives is null || g.Objectives.Count == 0) i.Add(new("quest.group.objectives.required", $"Quest group '{g.Id}' must contain objectives.", "objective_groups")); else foreach (var id in g.Objectives) { if (!ids.Contains(id)) i.Add(new("quest.group.objective.missing", $"Quest group '{g.Id}' references missing objective '{id}'.", "objective_groups")); memberships[id] = memberships.TryGetValue(id, out var count) ? count + 1 : 1; } }
        if (resource.ObjectiveGroups is null || resource.ObjectiveGroups.Count == 0) i.Add(new("quest.groups.required", "Quest must contain at least one objective group.", "objective_groups")); foreach (var id in ids) if (!memberships.TryGetValue(id, out var count) || count != 1) i.Add(new("quest.objective.group_membership", $"Objective '{id}' must belong to exactly one objective group.", "objective_groups")); return i;
    }
    public static IReadOnlyList<ValidationIssue> ValidateId(string? id, ActorIdPolicy policy = ActorIdPolicy.NewResource) { var i = new List<ValidationIssue>(); ValidateId(id, policy, i); return i; }
    private static void ValidateId(string? id, ActorIdPolicy policy, ICollection<ValidationIssue> i) { if (string.IsNullOrWhiteSpace(id) || !IdRegex().IsMatch(id) || (policy == ActorIdPolicy.NewResource && !NewRegex().IsMatch(id))) i.Add(new("quest.id.invalid", $"Quest ID '{id}' is invalid.", "id")); }
    [GeneratedRegex("^[a-z0-9][a-z0-9_.-]*$", RegexOptions.CultureInvariant)] private static partial Regex IdRegex(); [GeneratedRegex("^[a-z0-9][a-z0-9_-]*$", RegexOptions.CultureInvariant)] private static partial Regex NewRegex();
}
