<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.4.0.2</Version>
    <AssemblyVersion>0.4.0.2</AssemblyVersion>
    <FileVersion>0.4.0.2</FileVersion>
    <InformationalVersion>0.4.0.2</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\..\schema\dialogue-capacity-profile.json" LogicalName="DialogueCapacityProfile.json" />
  </ItemGroup>
</Project>
